//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediatelExercise1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MediatelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MediatelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediatelExercise1.MediatelResources", typeof(MediatelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a number in the range from -90 to 90.
        /// </summary>
        public static string ErrorMessage_LatitudeDecimal {
            get {
                return ResourceManager.GetString("ErrorMessage_LatitudeDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a number in the range from 0 to 90.
        /// </summary>
        public static string ErrorMessage_LatitudeDegrees {
            get {
                return ResourceManager.GetString("ErrorMessage_LatitudeDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a number in the range from 0 to 60.
        /// </summary>
        public static string ErrorMessage_LatitudeMinutes {
            get {
                return ResourceManager.GetString("ErrorMessage_LatitudeMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a number in the range from 0 to 60.
        /// </summary>
        public static string ErrorMessage_LatitudeSeconds {
            get {
                return ResourceManager.GetString("ErrorMessage_LatitudeSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a number in the range from -180 to 180.
        /// </summary>
        public static string ErrorMessage_LongitudeDecimal {
            get {
                return ResourceManager.GetString("ErrorMessage_LongitudeDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a number in the range from 0 to 90.
        /// </summary>
        public static string ErrorMessage_LongitudeDegrees {
            get {
                return ResourceManager.GetString("ErrorMessage_LongitudeDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a number in the range from 0 to 60.
        /// </summary>
        public static string ErrorMessage_LongitudeMinutes {
            get {
                return ResourceManager.GetString("ErrorMessage_LongitudeMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a number in the range from 0 to 60.
        /// </summary>
        public static string ErrorMessage_LongitudeSeconds {
            get {
                return ResourceManager.GetString("ErrorMessage_LongitudeSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string LabelLatitude {
            get {
                return ResourceManager.GetString("LabelLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string LabelLongitude {
            get {
                return ResourceManager.GetString("LabelLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string LabelSearch {
            get {
                return ResourceManager.GetString("LabelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string MapRequestVM_Email_DisplayLabel {
            get {
                return ResourceManager.GetString("MapRequestVM_Email_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °.
        /// </summary>
        public static string MapRequestVM_LatDegrees_DisplayLabel {
            get {
                return ResourceManager.GetString("MapRequestVM_LatDegrees_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;.
        /// </summary>
        public static string MapRequestVM_LatMinutes_DisplayLabel {
            get {
                return ResourceManager.GetString("MapRequestVM_LatMinutes_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        public static string MapRequestVM_LatSeconds_DisplayLabel {
            get {
                return ResourceManager.GetString("MapRequestVM_LatSeconds_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °.
        /// </summary>
        public static string MapRequestVM_LonDegrees_DisplayLabel {
            get {
                return ResourceManager.GetString("MapRequestVM_LonDegrees_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;.
        /// </summary>
        public static string MapRequestVM_LonMinutes_DisplayLabel {
            get {
                return ResourceManager.GetString("MapRequestVM_LonMinutes_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        public static string MapRequestVM_LonSeconds_DisplayLabel {
            get {
                return ResourceManager.GetString("MapRequestVM_LonSeconds_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string MapSearchRequestHistoryVM_City_DisplayLabel {
            get {
                return ResourceManager.GetString("MapSearchRequestHistoryVM_City_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string MapSearchRequestHistoryVM_Country_DisplayLabel {
            get {
                return ResourceManager.GetString("MapSearchRequestHistoryVM_Country_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date create.
        /// </summary>
        public static string MapSearchRequestHistoryVM_DateCreated_DisplayLabel {
            get {
                return ResourceManager.GetString("MapSearchRequestHistoryVM_DateCreated_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string MapSearchRequestHistoryVM_Email_DisplayLabel {
            get {
                return ResourceManager.GetString("MapSearchRequestHistoryVM_Email_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House number.
        /// </summary>
        public static string MapSearchRequestHistoryVM_HouseNumber_DisplayLabel {
            get {
                return ResourceManager.GetString("MapSearchRequestHistoryVM_HouseNumber_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latutitude.
        /// </summary>
        public static string MapSearchRequestHistoryVM_Latitude_DisplayLabel {
            get {
                return ResourceManager.GetString("MapSearchRequestHistoryVM_Latitude_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string MapSearchRequestHistoryVM_Longitude_DisplayLabel {
            get {
                return ResourceManager.GetString("MapSearchRequestHistoryVM_Longitude_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post code.
        /// </summary>
        public static string MapSearchRequestHistoryVM_PostCode_DisplayLabel {
            get {
                return ResourceManager.GetString("MapSearchRequestHistoryVM_PostCode_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result code.
        /// </summary>
        public static string MapSearchRequestHistoryVM_ResultCode_DisplayLabel {
            get {
                return ResourceManager.GetString("MapSearchRequestHistoryVM_ResultCode_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address search.
        /// </summary>
        public static string ViewHeaderIndex {
            get {
                return ResourceManager.GetString("ViewHeaderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Search Requests History.
        /// </summary>
        public static string ViewHeaderMapRequestsHistory {
            get {
                return ResourceManager.GetString("ViewHeaderMapRequestsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result.
        /// </summary>
        public static string ViewHeaderSearchAddress {
            get {
                return ResourceManager.GetString("ViewHeaderSearchAddress", resourceCulture);
            }
        }
    }
}
